services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    image: kafka-consumer:1.0
    container_name: kafka-consumer
    restart: unless-stopped

    volumes:
      - ${CONSUMER_CONFIG_DIR}:/app/config:ro
      - ${CONSUMER_LOG_DIR}:/data/logs
